issues:
  exclude-rules:
    # Exclude issues bypassing staticcheck.conf
    - linters:
        - staticcheck
      text: "SA1019:"
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - govet
    - bodyclose

linters-settings:
  errcheck:
    ignore: os:MkdirAll,net/http:Write,fmt:.*,io:Close,github.com/prometheus/client_golang/prometheus:Write,compress/gzip:.*,github.com/prometheus/common/expfmt:MetricFamilyToText
  gofmt:
    simplify: false

run:
  deadline: 5m
  tests: false